### ISSUE TITLE
Add Spanish frequency dicts from  Leipzig

### ISSUE THREAD

**Issue by jamesmaa** [MarvNC/yomitan-dictionaries#70]
**Mexico Web**
[Web_2015_1M_both.zip](https://github.com/user-attachments/files/16397546/Web_2015_1M_both.zip)
[Web_2015_1M_occurence.zip](https://github.com/user-attachments/files/16397547/Web_2015_1M_occurence.zip)
[Web_2015_1M_rank.zip](https://github.com/user-attachments/files/16397548/Web_2015_1M_rank.zip)
**Wikipedia**
[Wikipedia_2021_1M_occurence.zip](https://github.com/user-attachments/files/16397549/Wikipedia_2021_1M_occurence.zip)
[Wikipedia_2021_1M_both.zip](https://github.com/user-attachments/files/16397550/Wikipedia_2021_1M_both.zip)
[Wikipedia_2021_1M_rank.zip](https://github.com/user-attachments/files/16397551/Wikipedia_2021_1M_rank.zip)
**News**
[News_2023_1M_both.zip](https://github.com/user-attachments/files/16397552/News_2023_1M_both.zip)
[News_2023_1M_occurence.zip](https://github.com/user-attachments/files/16397553/News_2023_1M_occurence.zip)
[News_2023_1M_rank.zip](https://github.com/user-attachments/files/16397554/News_2023_1M_rank.zip)

**Comment by MarvNC** [comment]
These should be added in addition to [this](https://github.com/jamesmaa/spanish-wikitionary-freq-dict/releases)?

**Comment by MarvNC** [comment]
Closed in favor of https://github.com/StefanVukovic99/leipzig-to-yomitan
