### ISSUE TITLE
no onomatoproject dictionary file/link

### ISSUE THREAD

**Issue by shigetsune** [MarvNC/yomitan-dictionaries#73]
there's no dictionary file for yomitan in https://onomatoproject.com and there's to my knowledge no dictionary file in dl folder.

**Comment by MarvNC** [comment]
It's in [the folder](https://github.com/MarvNC/yomitan-dictionaries?tab=readme-ov-file#dictionary-collection) though?
`[JA-EN Onomatopoeia] Onomatoproject.zip`
