### ISSUE TITLE
English to English New-Oxford dictionary doesn't work

### ISSUE THREAD

**Issue by mammadno** [MarvNC/yomitan-dictionaries#75]
Hi.
I just tried to import **[New-Oxford-American-Dictionary](https://drive.google.com/drive/folders/1APj14ap2yMv0WZvSCEGJq9jfMUpZy6Ao?usp=sharing)** and got this error while I was trying to load it in the Yomitan extension `ExtensionError: Dictionary has invalid data in 'index.json'`

I should mention that Oxford Advanced Learner's Dictionary is alright and has no issues for me but New Oxford doesn't import at all.

![Error](https://github.com/user-attachments/assets/2b42ffb8-00b7-41aa-aefa-86db9d1da22b)

**Comment by MarvNC** [comment]
Had a look, seems you'll need to change `4` to `3` in the `index.json` file and it'll work.

**Comment by mammadno** [comment]
Did that.
Then .Zip them again.
Now there is another error: `ExtensionError: Dictionary has invalid data in 'term_bank_1.json'`

![error2](https://github.com/user-attachments/assets/62c358f5-5db8-4876-bada-a19a307df724)

**Comment by MarvNC** [comment]
Sorry idk then, please join the Yzk discord for help as someone there made the English dictionaries.

https://discord.gg/HZGdRbM9
