### ISSUE TITLE
Error importing [ZH-JA] 白水社 中国語辞典

### ISSUE THREAD

**Issue by n-manas** [MarvNC/yomitan-dictionaries#80]
Hello,

I tried importing [ZH-JA] 白水社 中国語辞典 on Google Chrome but got an "unknown error" message in the importer. Not sure about what could be causing it.

Thank you in advance for your help! This tool is really a godsend.

**Comment by MarvNC** [comment]
Sorry about the issue. Seems some people get that random error from time to time, please file an issue in the [Yomitan repository](https://github.com/yomidevs/yomitan).
